debug: false
spring:
  aop:
    proxy-target-class: true
  http:
    multipart:
      max-file-size: 10Mb
      max-request-size: 10Mb
  application:
    name: myApp01
  jmx:
    default-domain: myApp01
  session:
    store-type: redis
    redis:
      namespace: myapp
  redis:
    host: 192.168.10.30
    password: 1qaz!QAZ
security:
  oauth2:
    client:
      accessTokenUri: ${auth.protocol}://${auth.host}:${auth.port}/${auth.context}/oauth/token
      userAuthorizationUri: ${auth.protocol}://${auth.host}:${auth.port}/${auth.context}/oauth/authorize
      clientId: admin
      clientSecret: adminSecret
      scope: adminScope
      grant-type: code
      id: admin
    resource:
      token-info-uri: ${auth.protocol}://${auth.host}:${auth.port}/${auth.context}/oauth/check_token
zuul:
  routes:
    user:
      path: /user/**
      url: ${auth.protocol}://${auth.host}:${auth.port}/${auth.context}/user
    logout:
      path: /logout/**
      url: ${auth.protocol}://${auth.host}:${auth.port}/${auth.context}/myLogout
    authorize:
      path: /authorize/**
      url: http://172.17.192.121:9998/authorization
    audit:
      path: /audit/**
      url: http://172.17.192.121:9996/auditing
    resource:
      path: /resource/**
      url: http://172.17.192.121:9995/adminResource
  host:
    connect-timeout-millis: 90000000
    socket-timeout-millis: 90000000
server:
  context-path: /ui2
  port: 8081
  error:
    whitelabel:
      enabled: false
logging:
  level:
    org.springframework.security: DEBUG
auth:
  protocol: https
  host: saba.esata.ir
  port: 7090
  context: authentication
my:
  white-list:
    host: localhost:8081,172.17.192.121:8081,10.128.40.48
    origin: http://localhost:8081,http://172.17.192.121:8081
    methods: GET,POST
