debug: false
spring:
  aop:
    proxy-target-class: true
  http:
    multipart:
      max-file-size: 10Mb
      max-request-size: 10Mb
  application:
    name: adminUI02
  jmx:
    default-domain: adminUI02
security:
  oauth2:
    client:
      accessTokenUri: http://172.17.192.121:9999/authentication/oauth/token
      userAuthorizationUri: http://172.17.192.121:9999/authentication/oauth/authorize
      clientId: admin
      clientSecret: adminSecret
      scope: adminScope
      grant-type: password
      id: admin
    resource:
      token-info-uri: http://172.17.192.121:9999/authentication/oauth/check_token
zuul:
  routes:
    user:
      path: /user/**
      url: http://172.17.192.121:9999/authentication/user
    logout:
      path: /logout/**
      url: http://172.17.192.121:9999/authentication/myLogout
    authorize:
      path: /authorize/**
      url: http://172.17.192.121:9998/authorization
    audit:
      path: /audit/**
      url: http://172.17.192.5:8080/auditing
    resource:
      path: /resource/**
      url: http://172.17.192.5:8080/adminResource
  host:
    connect-timeout-millis: 90000000
    socket-timeout-millis: 90000000
server:
  context-path: /ui2
  port: 8081
  error:
    whitelabel:
      enabled: false
